version: "3.9"

services:
  backend:
    build: .
    container_name: trava_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trava
    depends_on:
      - db

  db:
    image: postgis/postgis:17-3.5
    container_name: trava_postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trava
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
    external: true
